FROM python:3.7-buster

# set work directory
RUN mkdir -p /home/app/web

WORKDIR /home/app/web

#env variables

ENV FLASK_APP run.py
ENV FLASK_RUN_HOST 0.0.0.0

# install system dependencies
RUN apt update

# install dependencies
RUN pip install --upgrade pip
COPY ./requirements.txt /home/app/web/requirements.txt
RUN pip install -r requirements.txt

# copy project
COPY . .


CMD ["flask", "run"]